FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN apt-get update && apt-get install -y \
    libffi-dev \
    libjpeg-dev \
    zlib1g-dev \
    && pip install --upgrade pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/


COPY bimebazar_web/docker-web-entrypoint.sh /docker-web-entrypoint.sh
RUN chmod +x /docker-web-entrypoint.sh

ENTRYPOINT ["/docker-web-entrypoint.sh"]

EXPOSE 8000

CMD ["python", "bimebazar_web/manage.py", "runserver", "0.0.0.0:8000"]
