FROM python:3.9-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN apk update && apk add --no-cache \
    gcc \
    libc-dev \
    libffi-dev \
    make \
    musl-dev \
    postgresql-dev \
    linux-headers \
    jpeg-dev \
    zlib-dev \
    && pip install gunicorn

RUN apk add --no-cache postgresql-libs

RUN pip install --upgrade pip

COPY requirements.txt /code/

RUN pip install -r requirements.txt

COPY . /code/

COPY bimebazar_web/docker-web-entrypoint.sh /docker-web-entrypoint.sh
RUN chmod +x /docker-web-entrypoint.sh

ENTRYPOINT ["/docker-web-entrypoint.sh"]

RUN adduser -D myuser
USER myuser

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "bimebazar_web.wsgi:application"]
