services:
  web:
    build:
      context: .
      dockerfile: bimebazar_web/Dockerfile
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=bimebazar_web.settings
      - PYTHONPATH=/code/bimebazar_web
    ports:
      - "8000:8000"
    command: python bimebazar_web/manage.py runserver 0.0.0.0:8000