FROM nginx:alpine

RUN apk add --no-cache gettext

COPY nginx/nginx.conf.template /etc/nginx/conf.d/default.conf.template

COPY nginx/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
