# Generated by Django 4.2.1 on 2024-08-02 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('genre', models.CharField(max_length=200, verbose_name='Genre')),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Published Date')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
